name: Shopee Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:

  run:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4

    - run: npm install

    - run: npx playwright install chromium

    - run: node index.js
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
